services:
  - type: web
    name: rice-disease-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON VERSION
        value: 3.12.3
